trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

jobs:
  - template: ci/job-rustfmt.yml
  - template: ci/job-check.yml
  - template: ci/job-test.yml
    parameters:
      name: test_stable
      toolchain: stable
      steps:
        - script: |
            cargo test --features unsafe_test_runner --test datatest_stable_unsafe
          displayName: cargo test --features unsafe_test_runner --test datatest_stable_unsafe
  - template: ci/job-test.yml
    parameters:
      name: test_nightly
      toolchain: nightly
