parameters:
  toolchain: stable
  features: []
jobs:
  - job: check
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: steps-install-rust.yml
        parameters:
          toolchain: ${{ parameters.toolchain }}
          components:
            - clippy
      - script: |
          cargo check --all --all-targets --features "${{ join(' ', parameters.features) }}"
        displayName: cargo check
      - script: |
          cargo clippy --all --features "${{ join(' ', parameters.features) }}"
        displayName: cargo clippy --all

